// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-_jZnaDxdSk9mG9S-Ae4jFnbk9Q17cxU',
    appId: '1:696907067067:web:a96bf88fcc53c26b53839e',
    messagingSenderId: '696907067067',
    projectId: 'reciclapp-d79a0',
    authDomain: 'reciclapp-d79a0.firebaseapp.com',
    storageBucket: 'reciclapp-d79a0.firebasestorage.app',
    measurementId: 'G-G0Z3R7RRR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9rEjKa2N0uDjSbsUfwb85HU68wkGkbCU',
    appId: '1:696907067067:android:bb7c4cc89370d57053839e',
    messagingSenderId: '696907067067',
    projectId: 'reciclapp-d79a0',
    storageBucket: 'reciclapp-d79a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCCLKAK91Y61FhxSG6eOUB7vvynE-N_e4',
    appId: '1:696907067067:ios:c8def6481f9b57c153839e',
    messagingSenderId: '696907067067',
    projectId: 'reciclapp-d79a0',
    storageBucket: 'reciclapp-d79a0.firebasestorage.app',
    iosBundleId: 'com.example.reciclapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCCLKAK91Y61FhxSG6eOUB7vvynE-N_e4',
    appId: '1:696907067067:ios:c8def6481f9b57c153839e',
    messagingSenderId: '696907067067',
    projectId: 'reciclapp-d79a0',
    storageBucket: 'reciclapp-d79a0.firebasestorage.app',
    iosBundleId: 'com.example.reciclapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-_jZnaDxdSk9mG9S-Ae4jFnbk9Q17cxU',
    appId: '1:696907067067:web:d66dd5ed6ec0359553839e',
    messagingSenderId: '696907067067',
    projectId: 'reciclapp-d79a0',
    authDomain: 'reciclapp-d79a0.firebaseapp.com',
    storageBucket: 'reciclapp-d79a0.firebasestorage.app',
    measurementId: 'G-944YPQ5C2R',
  );

}