// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5oeOkvUSsgapEVFxLFQ9DrnpAAuYrlSE',
    appId: '1:17353900917:web:314bf4df4160884583893c',
    messagingSenderId: '17353900917',
    projectId: 'reciclapp-hibrido',
    authDomain: 'reciclapp-hibrido.firebaseapp.com',
    storageBucket: 'reciclapp-hibrido.firebasestorage.app',
    measurementId: 'G-R40JVXLKXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNxJRLWC_F0HLyVHGRx9P7U961SLDSJeM',
    appId: '1:17353900917:android:72e1a0bc6c20fe9683893c',
    messagingSenderId: '17353900917',
    projectId: 'reciclapp-hibrido',
    storageBucket: 'reciclapp-hibrido.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9u0XXSxds_tziYIe6fD8N0Hi3Wu1dLM8',
    appId: '1:17353900917:ios:d3532bac6edd86d483893c',
    messagingSenderId: '17353900917',
    projectId: 'reciclapp-hibrido',
    storageBucket: 'reciclapp-hibrido.firebasestorage.app',
    iosBundleId: 'com.example.reciclapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9u0XXSxds_tziYIe6fD8N0Hi3Wu1dLM8',
    appId: '1:17353900917:ios:d3532bac6edd86d483893c',
    messagingSenderId: '17353900917',
    projectId: 'reciclapp-hibrido',
    storageBucket: 'reciclapp-hibrido.firebasestorage.app',
    iosBundleId: 'com.example.reciclapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5oeOkvUSsgapEVFxLFQ9DrnpAAuYrlSE',
    appId: '1:17353900917:web:806ac9fa4a8897d283893c',
    messagingSenderId: '17353900917',
    projectId: 'reciclapp-hibrido',
    authDomain: 'reciclapp-hibrido.firebaseapp.com',
    storageBucket: 'reciclapp-hibrido.firebasestorage.app',
    measurementId: 'G-77QLDG2MD1',
  );

}